### ISSUE TITLE
How to pass SslOptions to HttpTransport via Symfony service definition?

### ISSUE THREAD

**Issue by thomaskonrad** [bzikarsky/gelf-php#126]
I have defined my Gelf Symfony services as follows:

```
services:
    Gelf\Publisher:
        arguments:
            - '@Gelf\Transport\HttpTransport'
    Gelf\Transport\HttpTransport:
        arguments:
            - '%env(GRAYLOG_HOSTNAME)%'
            - '%env(GRAYLOG_PORT)%'
            - '%env(GRAYLOG_PATH)%'
            # This is where the `SslOptions` object would go.
```

The `HttpTransport` constructor looks like this:

```
 public function __construct(
        $host = self::DEFAULT_HOST,
        $port = self::DEFAULT_PORT,
        $path = self::DEFAULT_PATH,
        SslOptions $sslOptions = null
    ) {
```

How can I pass an `SslOptions` object here via the service definition? The class has no constructor, so I cannot simply use it as a service. Do I have to override `SslOptions`, make a service out of it, and pass the options to the constructor? Or what's the default way of specifying SSL options with this library?
