### ISSUE TITLE
Error with symfony/monolog-bundle and level "info"

### ISSUE THREAD

**Issue by julienfastre** [bzikarsky/gelf-php#157]
I use gelf-php with monolog-bundle and symfony version 5.4.40.

When I configure monolog like this, I do not encounter any error:

```yaml
services:
    monolog.gelf_handler:
        class: Monolog\Handler\GelfHandler
        arguments:
            - '@gelf.publisher'
            - "notice"

    gelf.publisher:
        class: Gelf\Publisher
        arguments: ['@gelf.ignore_error_transport']

    gelf.ignore_error_transport:
        class: Gelf\Transport\IgnoreErrorTransportWrapper
        arguments: ['@gelf.transport']

    gelf.transport:
        class: Gelf\Transport\UdpTransport
        arguments:
            - "%env(resolve:GELF_HOST)%"
            - "%env(resolve:GELF_PORT)%"

monolog:
    handlers:
        graylog:
            type: service
            id: monolog.gelf_handler
            level: info
            channels: ['!event', '!php']

        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
            bubble: false
```

But If I decrease the log level like this:

```diff
    monolog.gelf_handler:
        class: Monolog\Handler\GelfHandler
        arguments:
            - '@gelf.publisher'
-           - "notice"
+           - "info"
```

I encounter this errors:

```
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/julien/dev/app/sf5/vendor/graylog2/gelf-php/src/Gelf/Message.php on line 303
```

All the levels above "notice" does work (warning, error, ...).
